### PR TITLE
upkeep: rip `public/`

### LINKED ISSUE #10: upkeep: see if removing the `public` directory still yields a successful build and deploy
Both the building of the Hugo website and deploying it is handled by this GitHub action https://github.com/RMI-PACTA/rmi-pacta.github.io/blob/main/.github/workflows/hugo.yml

However, the website is also built and committed directly to `main` in the `public/` directory. 

If we remove that directory, the website SHOULD still build and render as expected.

### PR DESCRIPTION
**Pull request by jdhoffa**
Since this will depend on seeing if the `hugo.yml` is able to rebuild and deploy the entire site without the `public/` folder, the only real way to test it is to just merge this. 

Note: nothing is really lost, as the `public/` folder is very easily regenereted using the `blogdown::build_site()` command.

Closes #10

### CODE REVIEW

**Comment by cjyetman** [comment]
Also can't load this diff page to approve, du putting my approval here 😁

**Comment by jdhoffa** [comment]
FYI. I'm hoping that removing the `public` folder means there are no more PRs that are this size XD

**Comment by jdhoffa** [comment]
@cjyetman you didn't actually approve it

**Review by cjyetman — DISMISSED** [review]

**Comment by jdhoffa** [comment]
FYI looks like this didn't break anything! The website still builds and deploys to: https://rmi-pacta.github.io/

However, the action definitely won't build `.Rmd` (but that might actually be advantageous)
Relates to #22

**Pull request merged**
